version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - bodyclose

formatters:
  enable:
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
